spring:
  datasource:
    url: jdbc:mysql://ecomm-db.ctke0gscapdq.ap-south-1.rds.amazonaws.com:3306/ecomm_backend
    username: admin
    password: Kashi1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api3
  boot:
    admin:
      client:
        url: http://service-admin-server:80/
  mail:
    host: smtp.gmail.com
    port: 587
    username: kashi.sa200@gmail.com
    password: hdsw plfv kkjr orhh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082


