spring:
  datasource:
    url: jdbc:mysql://ecomm-db.ctke0gscapdq.ap-south-1.rds.amazonaws.com:3306/ecomm_backend
    username: admin
    password: Kashi1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api2
  boot:
    admin:
      client:
        url: http://service-admin-server:80/
management:
  endpoints:
    web:
      exposure:
        include: "*"
razorpay:
  key:
    id: rzp_test_9Rv894lScSIEg0
    secret: SCdIT3EPCfcNDwpBdmTnVt0s
server:
  port: 8081


